# Generated by Django 4.2.2 on 2024-01-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('players', models.IntegerField(choices=[(1, 'Single-player'), (2, 'Multiplayer'), (3, 'Ambos'), (4, 'Melhor com amigos!')], default=1)),
                ('synopsis', models.TextField()),
                ('connectivity', models.IntegerField(choices=[(1, 'Offline'), (2, 'Online'), (3, 'Ambos')], default=1)),
                ('wiki', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Point-and-click'), (2, 'Fighting'), (3, 'Shooter'), (4, 'Music'), (5, 'Platform'), (6, 'Puzzle'), (7, 'Racing'), (8, 'Real Time Strategy (RTS)'), (9, 'Role-playing (RPG)'), (10, 'Simulator'), (11, 'Sport'), (12, 'Strategy'), (13, 'Turn-based strategy (TBS)'), (14, 'Tactical'), (15, 'Quiz/Trivia'), (16, "Hack and slash/Beat 'em up"), (17, 'Pinball'), (18, 'Adventure'), (19, 'Arcade'), (20, 'Visual Novel'), (21, 'Indie'), (22, 'Card & Board Game'), (23, 'MOBA')])),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'PC'), (2, 'Xbox'), (3, 'Playstation'), (4, 'Switch'), (5, 'All')])),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='main.platform'),
        ),
    ]
