# Generated by Django 4.1.5 on 2023-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
