# Generated by Django 4.2.2 on 2023-06-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogo',
            new_name='Game',
        ),
    ]
