# Generated by Django 4.2.2 on 2023-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_jogo_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
