# Generated by Django 4.2.2 on 2023-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='quantity',
        ),
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.IntegerField(choices=[(1, 'PC'), (2, 'XBOX'), (3, 'PLAYSTATION'), (4, 'SWITCH')], default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(choices=[(1, 'Single player'), (2, 'Multiplayer'), (3, 'Better with friends!')], default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='synopsis',
            field=models.CharField(default='', max_length=300),
        ),
    ]
