# Generated by Django 4.2.2 on 2023-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_game_quantity_game_online_game_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='online',
            field=models.IntegerField(choices=[(1, 'Offline'), (2, 'Online'), (3, 'Both')], default=1),
        ),
    ]
