# Generated by Django 4.2.2 on 2023-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_game_platform_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.IntegerField(choices=[(1, 'PC'), (2, 'Xbox'), (3, 'Playstation'), (4, 'Switch'), (5, 'All')], default=1),
        ),
    ]
