# Generated by Django 4.2.2 on 2023-06-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_game_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='online',
            new_name='connectivity',
        ),
    ]
