# Generated by Django 4.2.2 on 2023-06-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.IntegerField(choices=[(1, 'Offline'), (2, 'Online'), (3, 'Both')])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'RPG'), (4, 'Strategy'), (5, 'Sports'), (6, 'Simulation'), (7, 'Puzzle'), (8, 'Racing'), (9, 'Shooter'), (10, 'Fighting'), (11, 'MOBA'), (12, 'RTS')])),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'PC'), (2, 'Xbox'), (3, 'Playstation'), (4, 'Switch'), (5, 'All')])),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField(choices=[(1, 'Single player'), (2, 'Multiplayer'), (3, 'Both'), (4, 'Better with friends!')])),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.ManyToManyField(to='main.connectivity')),
                ('genres', models.ManyToManyField(to='main.genre')),
                ('platforms', models.ManyToManyField(to='main.platform')),
                ('players', models.ManyToManyField(to='main.players')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='main.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='connectivity',
            field=models.ManyToManyField(to='main.connectivity'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='main.players'),
        ),
    ]
