# Generated by Django 4.2.2 on 2023-06-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_connectivity_connectivity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.IntegerField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'RPG'), (4, 'Strategy'), (5, 'Sports'), (6, 'Simulation'), (7, 'Puzzle'), (8, 'Racing'), (9, 'Shooter'), (10, 'Fighting'), (11, 'MOBA'), (12, 'Real-time Strategy'), (13, 'Visual Novel'), (14, 'Terror'), (15, "Beat 'em up"), (16, 'Platformer'), (17, 'Card game'), (18, 'Board game'), (19, 'Graphic adventure'), (20, 'Stealth'), (21, 'Interactive fiction'), (22, 'Turn-based strategy'), (23, 'Sandbox'), (24, 'Construction game'), (25, 'Roguelike'), (26, 'Metroidvania'), (27, 'Battle royale'), (28, 'Hack and slash'), (29, 'Rhythm game'), (30, 'Educational game')]),
        ),
    ]
