# Generated by Django 4.2.2 on 2023-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.DeleteModel(
            name='Connectivity',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='game',
            name='connectivity',
            field=models.IntegerField(choices=[(1, 'Offline'), (2, 'Online'), (3, 'Both')], default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(choices=[(1, 'Single player'), (2, 'Multiplayer'), (3, 'Both'), (4, 'Better with friends!')], default=1),
        ),
    ]
