# Generated by Django 4.2.2 on 2023-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_quiz_connectivity_remove_quiz_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
