# Generated by Django 4.2.2 on 2023-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_game_connectivity_alter_game_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(choices=[(1, 'Single-player'), (2, 'Multiplayer'), (3, 'Ambos'), (4, 'Melhor com amigos!')], default=1),
        ),
    ]
