# Generated by Django 4.2.2 on 2023-06-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
