# Generated by Django 4.2.2 on 2023-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_quiz_q1_alter_quiz_q10_alter_quiz_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_picture_tgr4726hf8783.jpg', upload_to='profile_pics'),
        ),
    ]
