# Generated by Django 4.2.2 on 2023-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q9',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q1',
            field=models.CharField(choices=[('playstation_1', 'Playstation 1'), ('playstation_2', 'Playstation 2'), ('playstation_3', 'Playstation 3'), ('playstation_4', 'Playstation 4'), ('playstation_5', 'Playstation 5'), ('playstation_psp', 'Playstation Portable (PSP)'), ('playsation_vita', 'Playstation Vita'), ('xbox', 'Xbox'), ('xbox_360', 'Xbox 360'), ('xbox_one', 'Xbox One'), ('xbox_x', 'Xbox Series S/X'), ('xbox_kinect', 'Kinect')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q2',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q3',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q4',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q5',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q6',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q7',
            field=models.CharField(choices=[('opção1', 'Opção 1'), ('opção2', 'Opção 2'), ('opção3', 'Opção 3')], default='opção1', max_length=50),
        ),
    ]
