# Generated by Django 4.2.2 on 2023-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_quiz_q1_alter_quiz_q2_alter_quiz_q3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='q1',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('pc', 'PC (Qualquer loja)'), ('cel_android', 'Android'), ('cel_ios', 'IOS'), ('playstation_1', 'Playstation 1'), ('playstation_2', 'Playstation 2'), ('playstation_3', 'Playstation 3'), ('playstation_4', 'Playstation 4'), ('playstation_5', 'Playstation 5'), ('playstation_psp', 'Playstation Portable (PSP)'), ('playstation_vita', 'Playstation Vita'), ('xbox_xbox', 'Xbox'), ('xbox_360', 'Xbox 360'), ('xbox_one', 'Xbox One'), ('xbox_x', 'Xbox Series S/X'), ('xbox_kinect', 'Kinect'), ('nintendo_nes', 'NES/Famicom'), ('nintendo_super', 'Super Nintendo'), ('nintendo_gameboy', 'Gameboy (Color/SP)'), ('nintendo_64', 'Nintendo 64'), ('nintendo_advance', 'Gameboy Advance'), ('nintendo_gamecube', 'Nintendo Gamecube'), ('nintendo_wii', 'Nintendo Wii'), ('nintendo_ds', 'Nintendo DS'), ('nintendo_3ds', 'Nintendo 3DS/2DS'), ('nintendo_wiiu', 'Nintendo Wii U'), ('nintendo_switch', 'Nintendo Switch'), ('sega_master', 'Master System'), ('sega_mega', 'Genesis (Mega Drive)'), ('sega_32x', 'Sega 32X'), ('sega_saturn', 'Sega Saturn'), ('sega_dreamcast', 'Dreamcast'), ('sega_gear', 'Game Gear'), ('atari_2500', 'Atari 2500'), ('atari_2600', 'Atari 2600'), ('atari_5200', 'Atari 5200'), ('atari_7800', 'Atari 7800'), ('atari_jaguar', 'Atari Jaguar (CD)'), ('snk_neogeo', 'NeoGeo (CD)'), ('snk_hyper', 'Hyper NeoGeo 64'), ('husdon_turbografx', 'TurboGrafx-16 (PC-Engine)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q2',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('action_beat_em_up', "Beat'em Up"), ('action_hack_slash', 'Hack-and-slash'), ('action_soulslike', 'Souls-like'), ('rpg_action', 'RPG de Ação (Action RPG)'), ('rpg_tatical', 'RPG Tático (Tactical RPG)'), ('rpg_turn_based', 'RPG por Turnos (Turn-Based RPG)'), ('rpg_mmorpg', 'MMORPG'), ('simulation_life', 'Simulação de Vida (Life Simulation)'), ('simulation_construction', 'Construção e Gerenciamento (Construction and Management)'), ('simulation_sandbox', 'Sandbox'), ('strategy_real_time', 'Estratégia em Tempo Real (Real-Time Strategy)'), ('strategy_turn_based', 'Estratégia por Turnos (Turn-Based Strategy)'), ('strategy_tower_defense', 'Tower Defense'), ('strategy_board_games', 'Jogos de Tabuleiro (Board Games)'), ('strategy_moba', 'Multiplayer Online Battle Arena (MOBA)'), ('fighting_2d', '2D Fighting'), ('fighting_3d', '3D Fighting'), ('fighting_platform', 'Luta em Plataforma'), ('shooter_fps', 'Tiro em Primeira Pessoa (FPS)'), ('shooter_tps', 'Tiro em Terceira Pessoa (TPS)'), ('shooter_hero', 'Hero Shooter'), ('shooter_mmofps', 'MMOFPS'), ('terror_survival', 'Horror de Sobrevivência (Survival Horror)'), ('terror_psyco', 'Horror Psicológico (Psychological Horror)'), ('adventure', 'Aventura'), ('open_world', 'Mundo aberto'), ('sports', 'Esportes'), ('racing', 'Corrida'), ('battle_royale', 'Battle Royale'), ('survival', 'Sobrevivência'), ('puzzle', 'Quebra cabeça'), ('platformer', 'Plataforma (Platformer)'), ('metroidvania', 'Metroidvania'), ('rogue', 'Roguelike & Roguelite'), ('endless_runner', 'Corrida infinita'), ('music_rythm', 'Música e Ritmo'), ('card', 'Jogos de Cartas'), ('visual_novel', 'Visual Novel'), ('contemplative', 'Jogos Contemplativos'), ('educational', 'Jogos Educativos'), ('narrative', 'Jogos de Narrativa'), ('social', 'Social Game')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q3',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('single_on', 'Singleplayer online'), ('single_off', 'Singleplayer offline'), ('multi_on', 'Multiplayer online'), ('multi_coop_local', 'Multiplayer co-op local'), ('multi_coop_online', 'Multiplayer co-op online'), ('multi_service', 'Live service')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q4',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('casual', 'Casual'), ('challenge', 'Desafiador')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q5',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('retro', 'Retrô'), ('atual', 'Atual'), ('2d_hd', '2D-HD'), ('ladrilho', 'Ladrilho'), ('cel_shading', 'Cel Shading'), ('realistic', 'Realista'), ('voxel', 'Voxel')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q6',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('third_person_fixed', 'Terceira pessoa - Câmera fixa'), ('third_person_interactive', 'Terceira pessoa - Câmera interativa'), ('third_person_companion', 'Terceira pessoa - Câmera acompanhante'), ('first_person', 'Primeira pessoa'), ('side_scrolling', 'Side Scrolling'), ('parallax', 'Paralaxe'), ('isometric', 'Isométrico'), ('top_down', 'Top-down'), ('multiplane', 'Multiplano (Final Fantasy Tactics / Doom)'), ('static_camera', 'Câmera estática')], max_length=25),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q7',
            field=models.CharField(choices=[('random', 'Me surpreenda!'), ('price_4', 'Full-Price (R$250,00 ao infinito e além)'), ('price_3', 'Centenas (R$100,00 a R$249,99)'), ('price_2', 'Menos de 100 (R$20,00 a R$100,00)'), ('price_1', 'Pechincha (até R$19,99)'), ('free_to_play', 'Free-to-play'), ('pay_to_win', 'Pay-To-Win'), ('pay_to_fast', 'Pay-To-Fast')], max_length=25),
        ),
    ]
